'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readPref=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const readText=(k,f)=>{try{return localStorage.getItem(k)||f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v))}catch{}};
const saved=readPref('esta_view_v2',{});
const state={lang:readText('esta_lang_pref','tr')==='ru'?'ru':'tr',theme:readText('esta_theme_pref','dark')==='light'?'light':'dark',route:'ozet',vat:saved.vat==='kdvli'?'kdvli':'kdvsiz',period:['all','3','6','12'].includes(saved.period)?saved.period:'6',start:saved.start||null,end:saved.end||null,categories:Array.isArray(saved.categories)?saved.categories:null,general:Array.isArray(saved.general)?saved.general:['harcama','tahsilat','hakedis'],busy:false,source:'network',received:null,sort:{}};
let DATA=null,chartRegistry={},searchIndex=[],noticeTimer,dialogOpener;
const t=s=>state.lang==='ru'?(TRANSLATIONS_RU[s]||s):s;
const fmt=n=>Number.isFinite(n)?n.toLocaleString(state.lang==='ru'?'ru-RU':'tr-TR',{maximumFractionDigits:2}):'—';
const money=n=>`${fmt(typeof n==='string'?Core.parseM(n):n)} ${t('milyon ₽')}`;
const pct=n=>Number.isFinite(n)?`${fmt(n)}%`:'—';
const month=s=>{if(state.lang!=='ru')return s;const a=['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'],b=['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'];const [m,y]=s.split('.');return a.includes(m)?`${b[a.indexOf(m)]}.${y}`:s};
const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',bank:'M3 10h18 M5 10v9 M10 10v9 M14 10v9 M19 10v9 M3 21h18 M3 7l9-5 9 5z',file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6 M8 13h8 M8 17h5',layers:'M12 3L2 8l10 5 10-5z M2 12l10 5 10-5 M2 16l10 5 10-5',wallet:'M3 6h17v15H3z M3 6V3h15v3 M15 12h6v5h-6z',site:'M3 21V9h18v12 M7 9V4h10v5 M7 13h2 M15 13h2 M7 17h2 M15 17h2 M10 21v-4h4v4',chart:'M3 3v18h18 M6 15l4-5 4 3 6-8',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',refresh:'M20 7v5h-5 M4 17v-5h5 M6 6a8 8 0 0 1 13 1l1 5 M4 12l1 5a8 8 0 0 0 13 1',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',sun:'M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',moon:'M21 13a9 9 0 1 1-10-10 7 7 0 0 0 10 10',logout:'M9 3H3v18h6 M10 12h11 M17 8l4 4-4 4',more:'M5 12h.01 M12 12h.01 M19 12h.01',close:'M6 6l12 12 M6 18L18 6',info:'M12 11v6 M12 7h.01 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',arrow:'M5 12h14 M14 7l5 5-5 5',up:'M6 14l6-6 6 6',down:'M6 10l6 6 6-6',sort:'M4 6h16 M7 12h10 M10 18h4',expand:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',check:'M5 12l4 4L19 6'};
const icon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`;
const NAV=[['ozet','Özet','grid'],['avans','Avans','bank'],['hakedis','Hakediş','file'],['acikisler','Açık İşler','layers'],['harcamalar','Harcamalar','wallet'],['saha','Saha','site'],['grafikler','Grafikler','chart']];
const titles={ozet:'Finansal Özet',avans:'Avans',hakedis:'Hakediş',acikisler:'Açık İşler',harcamalar:'Harcamalar',saha:'Saha İlerleme',grafikler:'Grafikler'};
const ORDER_KEYS={nav:'esta_nav_order_v1',gauge:'esta_gauge_order_v1',saha:'esta_saha_order_v1',acik:'esta_acikisler_order_v1',harcama:'esta_harcama_order_v1'};
function ordered(arr,kind,label){const order=readPref(ORDER_KEYS[kind],[]);if(!Array.isArray(order))return [...arr];return [...arr].sort((a,b)=>{let x=order.indexOf(label(a)),y=order.indexOf(label(b));return (x<0?1e6:x)-(y<0?1e6:y)})}
function persist(){save('esta_view_v2',{vat:state.vat,period:state.period,start:state.start,end:state.end,categories:state.categories,general:state.general})}
function theme(){document.documentElement.dataset.theme=state.theme;document.documentElement.lang=state.lang;document.querySelector('meta[name=theme-color]').content=state.theme==='dark'?'#0f1115':'#f3f5f8'}
function status(){const text=state.source==='cache'?`${t('Son kayıtlı rapor')}${!navigator.onLine?' · '+t('Çevrimdışı'):''}`:!navigator.onLine?t('Çevrimdışı'):t('Veri alındı');return `<span class="status ${state.source==='cache'||!navigator.onLine?'warning':''}">${esc(text)}</span>`}
function shell(){theme();$('#sidebar').innerHTML=`<div class="brand"><img src="icon-shield.png" alt="ESTA"><div><b>ESTA</b><small>CONSTRUCTION</small></div></div><div class="project-badge"><div class="project-mark">E</div><div><strong>${esc(DATA?.meta.project||'110 SPPC')}</strong><small>Severstal</small></div></div><div class="nav-caption">${t('Proje yönetimi')}</div><nav class="nav-list" aria-label="${t('Menü')}">${ordered(NAV,'nav',x=>x[0]).map(([key,label,img])=>`<a class="nav-link ${state.route===key?'active':''}" href="#${key}" title="${t(label)}" ${state.route===key?'aria-current="page"':''}>${icon(img)}<span>${t(label)}</span></a>`).join('')}</nav><div class="sidebar-foot"><button class="btn ghost" data-action="reorder">${icon('sort')}${t('Düzeni düzenle')}</button><button class="btn ghost" data-action="logout">${icon('logout')}${t('Çıkış Yap')}</button><small>ESTA · 110 SPPC</small></div>`;
$('#topbar').innerHTML=`<div class="crumb"><span>${esc(DATA?.meta.project||'110 SPPC')}</span><span>/</span><strong>${t(titles[state.route])}</strong></div><div class="mobile-brand"><img src="icon-shield.png" alt="ESTA"><span>${esc(DATA?.meta.project||'110 SPPC')}</span></div><div class="toolbar"><button class="btn search-button" data-action="search" aria-label="${t('Ara')}">${icon('search')}<span>${t('Ara')}</span><kbd>⌘ K</kbd></button><button class="icon-btn" data-action="lang" aria-label="${t('Dil')}: ${state.lang==='tr'?'Русский':'Türkçe'}">${state.lang.toUpperCase()}</button><button class="icon-btn" data-action="theme" aria-label="${t(state.theme==='dark'?'Açık tema':'Koyu tema')}">${icon(state.theme==='dark'?'sun':'moon')}</button><button class="icon-btn desktop-only" data-action="refresh" aria-label="${t('Yenile')}" ${state.busy?'disabled':''}>${icon('refresh')}</button></div>`;
const customNav=readPref(ORDER_KEYS.nav,[]);const mobileKeys=Array.isArray(customNav)&&customNav.length?ordered(NAV,'nav',x=>x[0]).slice(0,4).map(x=>x[0]):['ozet','hakedis','harcamalar','saha'];$('#mobileNav').setAttribute('aria-label',t('Menü'));$('#mobileNav').innerHTML=mobileKeys.map(key=>{const [,label,img]=NAV.find(x=>x[0]===key);return `<a href="#${key}" class="${state.route===key?'active':''}" ${state.route===key?'aria-current="page"':''}>${icon(img,19)}<span>${t(label)}</span></a>`}).join('')+`<button data-action="more" class="${!mobileKeys.includes(state.route)?'active':''}" aria-label="${t('Diğer')}">${icon('more',20)}<span>${t('Diğer')}</span></button>`;
$('#footer').innerHTML=`<span>ESTA Construction · ${esc(DATA?.meta.project||'110 SPPC')}</span><span>${t('Tutarlar milyon RUB (₽)')} · ${t('Rapor tarihi')}: ${esc(DATA?.meta.date||'—')}${DATA?.meta.generatedAt?' · '+t('Veri üretimi')+': '+esc(new Date(DATA.meta.generatedAt).toLocaleString(state.lang==='ru'?'ru-RU':'tr-TR')):''}</span>`;}
function pageHead(){return `<div class="page-head"><div><div class="eyebrow">110 SPPC / ${t('Finans ve saha raporu')}</div><h1>${t(titles[state.route])}</h1><p>${t('Rapor tarihi')}: <strong>${esc(DATA.meta.date)}</strong> &nbsp;·&nbsp; ${t('Tutarlar milyon RUB (₽)')}</p></div><div class="page-actions">${status()}<button class="btn" data-action="refresh" ${state.busy?'disabled':''}>${icon('refresh')}${t(state.busy?'Yenileniyor':'Yenile')}</button><button class="btn primary" data-action="report">${icon('download')}${t('Rapor indir')}</button></div></div>`}
const empty=(title='Henüz kayıt yok',description='Bu bölüm için rapor verisi bulunmuyor.')=>`<div class="empty">${icon('file',28)}<h2>${t(title)}</h2><p>${t(description)}</p></div>`;
const progress=(n,color='')=>`<div class="progress ${color}" role="progressbar" aria-label="${t('Oran')}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Core.width(n)}" aria-valuetext="${pct(n)}"><span style="width:${Core.width(n)}%"></span></div>`;
const kv=(label,value,sub=false)=>`<div class="kv ${sub?'sub':''}"><span>${esc(t(label))}</span><strong class="num">${esc(value)}</strong></div>`;
const amount=(value)=>`${fmt(Core.parseM(value))}<small>${t('milyon ₽')}</small>`;
function render(){if(!DATA)return;chartRegistry={};shell();const views={ozet:overview,avans:advances,hakedis:payments,acikisler:openWorks,harcamalar:expenses,saha:site,grafikler:graphs};$('#main').innerHTML=pageHead()+`<div class="fade-in">${views[state.route]()}</div>`;$('#main').setAttribute('aria-busy','false');buildSearch();persist();}
function route(){const key=location.hash.slice(1).split('?')[0];state.route=NAV.some(n=>n[0]===key)?key:'ozet';if(DATA){render();window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true})}else shell()}
function kpi(g,i){const s=Core.gaugeStats(g,DATA),base=t(s.base);const special=['Toplam Tahsilat','Saha Tahakkuk','Brüt Hakediş'].includes(g.label);return `<article class="kpi ${i<4?'featured':'secondary'}" id="${Core.id('gauge',g.label)}"><div class="kpi-label"><span>${esc(t(g.label))}</span><button data-action="formula" data-key="${esc(g.label)}" aria-label="${esc(t(g.label)+' · '+t('Hesaplama'))}">${icon('info',16)}</button></div><div class="kpi-value amount">${amount(g.big)}</div>${progress(s.pct,g.label==='Toplam Tahsilat'?'green':g.label==='Toplam Harcama'?'blue':'')}<div class="kpi-sub"><b>${pct(s.pct)}</b> · ${esc(base)}${special?`<br>${t('Sözleşme oranı')}: ${pct(s.contractPct)}`:''}</div></article>`}
function contract(c){return `<details><summary>${esc(t(c.label.replace(/ — .*/,'')))}${c.label.includes(' — ')?' · '+esc(c.label.split(' — ')[1]):''}</summary><div class="contract-total num">${money(c.total)}</div>${c.items.map(([l,v])=>kv(l,money(v))).join('')}</details>`}
function deadline(label,days,date){return `<div class="date-row"><div><h3>${label}</h3><small>${esc(date)}</small></div><div style="text-align:right"><strong class="num">${fmt(Math.abs(days))}</strong><small>${t(days<0?'gün gecikme':'gün kaldı')}</small></div></div>`}
function overview(){const initial=['Toplam Tahsilat','Toplam Harcama','Banka Bakiye','Açık İşler','Saha Tahakkuk','Brüt Hakediş','Avans Kesintisi','Borç'];const base=[...DATA.gauges].sort((a,b)=>initial.indexOf(a.label)-initial.indexOf(b.label));const g=ordered(base,'gauge',x=>x.label);return `<div class="kpi-grid">${g.slice(0,4).map(kpi).join('')}</div><div class="dashboard-columns"><div class="panel"><div class="panel-head"><div><h2>${t('Dönemsel karşılaştırma')}</h2><p>${t('Harcama')} / ${t('Tahsilat')} / ${t('Brüt Hakediş')}</p></div>${periodButtons()}</div>${generalChart('overview')}<button class="link-btn" data-action="goto" data-key="grafikler">${t('Tümünü gör')}${icon('arrow',16)}</button></div><div class="stack"><div class="panel"><div class="panel-head"><h2>${t('Sözleşmeler')}</h2>${icon('file')}</div><div class="meta">${t('Güncel Sözleşme Bedeli')}</div><div class="contract-total num">${money(DATA.contractCurrent.total)}</div><div class="meta">${t('Toplam Potansiyel Sözleşme Bedeli')}</div><div class="contract-total num">${money(DATA.contractPotential.total)}</div><button class="link-btn" data-action="contracts">${t('Sözleşme detayları')}${icon('arrow',16)}</button></div><div class="panel"><h2>${t('Süreç Takvimi')}</h2>${deadline('CMP',DATA.kalanGun.cmpGun,DATA.kalanGun.cmpTarih)}${deadline('PNR',DATA.kalanGun.pnrGun,DATA.kalanGun.pnrTarih)}<p class="meta">${t('Rapor tarihine göre kalan gün')}<br>${t('Geçen gün oranı')} (PNR): ${pct(DATA.kalanGun.gecenPnr)}</p></div></div></div><div class="section-row"><h2>${t('Ek göstergeler')}</h2><button class="link-btn" data-action="reorder" data-key="gauge">${icon('sort',16)}${t('Düzeni düzenle')}</button></div><div class="kpi-grid">${g.slice(4).map((v,i)=>kpi(v,i+4)).join('')}</div><div class="section-row"><h2>${t('Saha İlerleme')}</h2><button class="link-btn" data-action="goto" data-key="saha">${t('Tümünü gör')}${icon('arrow',16)}</button></div><div class="card-grid">${ordered(DATA.sahaItems,'saha',x=>x.name).slice(0,3).map(workCard).join('')}</div>`}
function periodButtons(){return `<div class="segmented" aria-label="${t('Dönem')}">${[['3','Son 3 Ay'],['6','Son 6 Ay'],['12','Son 12 Ay'],['all','Tüm dönem']].map(([key,label])=>`<button data-action="period" data-key="${key}" aria-pressed="${state.period===key}" class="${state.period===key?'active':''}">${t(label)}</button>`).join('')}</div>`}
const COLORS=['var(--blue)','var(--green)','var(--gold)','#ba9bed','#e99978','#72c8d4','#dc98bc','#b5c777','#ddbb83','#92a9d8','#a0c6af','#ca9fa0'];
function chart(key,months,series){chartRegistry[key]={months,series};if(!months.length)return empty();if(!series.length)return empty('Seçili seri yok','En az bir kalem seç.');const vals=series.flatMap(s=>s.values).filter(Number.isFinite);if(!vals.length)return empty();const min=Math.min(0,...vals),max=Math.max(0,...vals);const low=min<0?min*1.15:0,high=max>0?max*1.15:1,range=high-low||1;const w=Math.max(640,months.length*42),h=270,L=62,R=20,T=24,B=48;const x=i=>L+(months.length>1?i*(w-L-R)/(months.length-1):0),y=v=>T+(high-v)/range*(h-T-B);let svg='';for(let i=0;i<=4;i++){const v=low+(high-low)*i/4,yy=y(v);svg+=`<line class="chart-grid" x1="${L}" y1="${yy}" x2="${w-R}" y2="${yy}"/><text x="${L-10}" y="${yy+4}" text-anchor="end">${fmt(Math.round(v))}</text>`}const skip=Math.max(1,Math.ceil(months.length/12));months.forEach((m,i)=>{if(i%skip===0||i===months.length-1)svg+=`<text x="${x(i)}" y="${h-16}" text-anchor="middle">${esc(month(m))}</text>`});series.forEach((s,si)=>{let path='',started=false;const color=s.color||COLORS[si%COLORS.length];s.values.forEach((v,i)=>{if(!Number.isFinite(v)){started=false;return}path+=(started?'L':'M')+x(i)+','+y(v)+' ';started=true});svg+=`<path d="${path}" fill="none" stroke="${color}" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/>`;s.values.forEach((v,i)=>{if(!Number.isFinite(v))return;svg+=`<circle class="chart-dot" cx="${x(i)}" cy="${y(v)}" r="5" fill="${color}" tabindex="0" role="button" data-action="chart-point" data-key="${key}" data-index="${i}" aria-label="${esc(month(months[i])+' · '+t(s.label)+' '+money(v))}"><title>${esc(month(months[i])+' · '+t(s.label)+': '+money(v))}</title></circle>`})});return `<div class="chart-scroll"><svg class="chart-svg" viewBox="0 0 ${w} ${h}" role="group" aria-label="${t('Dönemsel karşılaştırma')}">${svg}</svg></div><div class="legend">${series.map((s,i)=>`<span><i style="--series:${s.color||COLORS[i%COLORS.length]}"></i>${esc(t(s.label))}</span>`).join('')}</div><p class="meta" style="margin-top:14px">${esc(month(months[0]))} — ${esc(month(months.at(-1)))} · ${t('Tutarlar milyon RUB (₽)')}</p><div class="panel-head" style="margin:6px 0 0"><p>${t('Değerleri görmek için bir noktaya dokun.')}</p><button class="link-btn" data-action="chart-data" data-key="${key}">${icon('expand',16)}${t('Grafik verileri')}</button></div>`}
function trimSeries(months,series){const start=state.period==='all'?0:Math.max(0,months.length-Number(state.period));return [months.slice(start),series.map(s=>({...s,values:s.values.slice(start)}))]}
function generalChart(key){const g=Core.generalSeries(DATA);const series=g.series.filter(s=>key==='overview'||state.general.includes(s.key)).map(s=>({...s,color:{harcama:'var(--blue)',tahsilat:'var(--green)',hakedis:'var(--gold)'}[s.key]}));return chart(key,...trimSeries(g.months,series))}
function advances(){const idx=state.vat==='kdvli'?2:1;const group=(label,rows,pIndex)=>`<div class="panel"><div class="panel-head"><h2>${t(label)}</h2><span class="badge">${t(state.vat==='kdvli'?"KDV'li":"KDV'siz")}</span></div>${rows.length?rows.map(([l,a,b,p],i)=>kv(l,money(idx===2?b:a)+(i===pIndex?' · '+pct(Core.ratio(Core.parseM(rows[i][1]),Core.parseM(rows[0][1]))):p!=null?' · '+pct(p):''))).join(''):empty()}</div>`;return `<div class="filters"><div class="segmented" aria-label="KDV">${[['kdvsiz',"KDV'siz"],['kdvli',"KDV'li"]].map(([key,label])=>`<button data-action="vat" data-key="${key}" class="${state.vat===key?'active':''}" aria-pressed="${state.vat===key}">${t(label)}</button>`).join('')}</div></div><div class="two-col">${group('Severstal Avans Tablosu',DATA.avansSummary,2)}<div class="panel"><h2>${t('Potansiyel Düşülecek Banka Mektubu')}</h2><div class="contract-total num">${money(DATA.potansiyelDusulecek[state.vat])}</div><span class="badge">${t(state.vat==='kdvli'?"KDV'li":"KDV'siz")}</span></div>${group('Banka Garantili',DATA.bankaGarantili,1)}${group('Banka Garantisiz',DATA.bankaGarantisiz,1)}</div>`}
function table(headers,rows,foot='',responsive=true){if(!rows.length)return empty();return `<div class="table-wrap ${responsive?'responsive':''}"><table><thead><tr>${headers.map((h,i)=>`<th scope="col" class="${i?'num':''}">${esc(t(h))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td data-label="${esc(t(headers[i]))}" class="${i?'num':'table-title'}">${c}</td>`).join('')}</tr>`).join('')}</tbody>${foot?`<tfoot><tr>${foot.map((c,i)=>`<td data-label="${esc(t(headers[i]))}" class="${i?'num':''}">${c}</td>`).join('')}</tr></tfoot>`:''}</table></div>`}
function payments(){const totalReceipt=Core.sum(DATA.monthlyNet.map(x=>x.tahsilat)),totalNet=Core.sum(DATA.monthlyNet.map(x=>x.net));return `<div class="two-col"><div class="panel"><div class="panel-head"><h2>${t('Brüt Hakediş Detayı')}</h2></div><div class="contract-total">${money(DATA.brutHakedisToplam)}</div>${DATA.brutHakedisDetay.map(([l,v])=>kv(l,money(v))).join('')}</div><div class="panel"><h2>${t('Kesintiler')}</h2>${DATA.kesintiler.map(([l,v,p])=>kv(l,money(v)+(p!=null?' · '+pct(p):''),/^(Banka Garant|Garanti Kesintisi %)/.test(l))).join('')}</div></div><div class="section-row"><h2>${t('Brüt Hakediş Aylık Dağılım')}</h2>${periodButtons()}</div><div class="panel">${chart('brut',...trimSeries(DATA.monthlyBrut.map(x=>x.m),[{label:'Brüt Hakediş',values:DATA.monthlyBrut.map(x=>x.v),color:'var(--gold)'}]))}</div><div class="section-row"><h2>${t('Tahsilat ve Net Hakediş')}</h2></div><div class="panel"><div class="two-col"><div><div class="meta">${t('Tahsilat')} · ${t('Tüm dönem')}</div><div class="contract-total num">${money(totalReceipt)}</div></div><div><div class="meta">${t('Net Hakediş')} · ${t('Tüm dönem')}</div><div class="contract-total num">${money(totalNet)}</div></div></div>${chart('net',...trimSeries(DATA.monthlyNet.map(x=>x.m),[{label:'Tahsilat',values:DATA.monthlyNet.map(x=>x.tahsilat),color:'var(--green)'},{label:'Net Hakediş',values:DATA.monthlyNet.map(x=>x.net),color:'var(--gold)'}]))}</div><div class="section-row"><h2>${t('Yapılan Brüt Hakedişler')}</h2></div>${table(['Kalem','Tutar','Kayıt sayısı'],Core.monthlyCategories(DATA).map(k=>[`<button class="table-action" id="${Core.id('payment',k.name)}" data-action="payment" data-key="${esc(k.name)}">${esc(t(k.name))} ↗</button>`,money(k.total),fmt(k.months.length)]))}`}
function openWorks(){const a=DATA.hakedisTotals.kdvHaric,b=DATA.hakedisTotals.kdvli,actual=Core.parseM(a.finansal),gross=Core.parseM(a.brut);let items=ordered(DATA.hakedisTipleri,'acik',x=>x[0]);if(state.sort.open==='value')items.sort((x,y)=>(Core.parseM(y[1])-Core.parseM(y[2]))-(Core.parseM(x[1])-Core.parseM(x[2])));return `<div class="kpi-grid"><div class="kpi"><div class="kpi-label">${t('Saha Finansal İlerleme')}</div><div class="kpi-value">${amount(a.finansal)}</div></div><div class="kpi"><div class="kpi-label">${t('Brüt Hakediş')}</div><div class="kpi-value">${amount(a.brut)}</div></div><div class="kpi featured"><div class="kpi-label">${t('Açık İşler Tutarı')}</div><div class="kpi-value">${fmt(actual-gross)}<small>${t('milyon ₽')}</small></div></div><div class="kpi"><div class="kpi-label">${t('Hakedişe dönüşen')}</div><div class="kpi-value">${pct(Core.ratio(gross,actual))}</div>${progress(Core.ratio(gross,actual))}</div></div><div class="section-row"><h2>${t('İş grupları')}</h2><div class="toolbar"><button class="btn" data-action="sort-open">${icon('sort')}${t('Fark')}</button><button class="icon-btn" data-action="reorder" data-key="acik" aria-label="${t('Sıralama')}">${icon('layers')}</button></div></div>${table(['Kalem','Finansal İlerleme','Brüt Hakediş','Fark','Oran'],items.map(([name,fin,brut])=>[`<span id="${Core.id('open',name)}">${esc(t(name))}</span>`,money(fin),money(brut),money(Core.parseM(fin)-Core.parseM(brut)),`<div class="table-progress"><span>${pct(Core.ratio(Core.parseM(brut),Core.parseM(fin)))}</span>${progress(Core.ratio(Core.parseM(brut),Core.parseM(fin)))}</div>`]),[t('Toplam (KDV hariç)'),money(a.finansal),money(a.brut),money(actual-gross),pct(Core.ratio(gross,actual))])}<div class="panel" style="margin-top:20px"><h2>${t("Toplam (KDV'li)")}</h2>${kv('Finansal İlerleme',money(b.finansal))}${kv('Brüt Hakediş',money(b.brut))}${kv('Oran',pct(Core.ratio(Core.parseM(b.brut),Core.parseM(b.finansal))))}</div>`}
function range(){const months=DATA.harcamalar?.aylar||[];let start=months.indexOf(state.start),end=months.indexOf(state.end);if(start<0)start=0;if(end<0)end=months.length-1;if(start>end)start=Math.max(0,end);return {months,start,end,total:Core.sum((DATA.harcamalar?.toplam.degerler||[]).slice(start,end+1))}}
function expenseFilters(){const r=range();const opts=selected=>r.months.map((m,i)=>`<option value="${esc(m)}" ${i===selected?'selected':''}>${esc(month(m))}</option>`).join('');return `<div class="filters"><div class="segmented" aria-label="${t('Dönem')}">${[['all','Tüm dönem'],['1','Son Ay'],['3','Son 3 Ay'],['6','Son 6 Ay'],['12','Son 12 Ay']].map(([key,label])=>`<button data-action="expense-period" data-key="${key}" class="${r.end===r.months.length-1&&r.start===(key==='all'?0:Math.max(0,r.months.length-Number(key)))?'active':''}">${t(label)}</button>`).join('')}</div><label class="field">${t('Başlangıç')}<select id="rangeStart">${opts(r.start)}</select></label><label class="field">${t('Bitiş')}<select id="rangeEnd">${opts(r.end)}</select></label></div>`}
function expenses(){if(!DATA.harcamalar?.aylar.length)return empty();const r=range();let categories=ordered(DATA.harcamalar.kategoriler,'harcama',x=>x.ad);if(state.sort.expense==='value')categories.sort((a,b)=>Core.sum(b.aylik.slice(r.start,r.end+1))-Core.sum(a.aylik.slice(r.start,r.end+1)));return `${expenseFilters()}<div class="panel"><div class="panel-head"><div><h2>${t('Toplam Harcama (Seçili Dönem)')}</h2><p>${esc(month(r.months[r.start]))} — ${esc(month(r.months[r.end]))}</p></div><div class="contract-total num" style="margin:0">${money(r.total)}</div></div></div><div class="info-line">${icon('info')}<span>${t('Kayıt dönemi')}: ${esc(month(r.months[0]))} — ${esc(month(r.months.at(-1)))}. ${t('Özet ve aylık kayıtların kapsamı farklı olabilir.')}</span></div><div class="section-row"><h2>${t('Harcama Kalemleri')}</h2><div class="toolbar"><button class="btn" data-action="sort-expense">${icon('sort')}${t('Tutar')}</button><button class="icon-btn" data-action="reorder" data-key="harcama" aria-label="${t('Sıralama')}">${icon('layers')}</button></div></div>${table(['Kalem','Dönem toplamı','Pay'],categories.map(k=>{const total=Core.sum(k.aylik.slice(r.start,r.end+1));return [`<button class="table-action" id="${Core.id('expense',k.ad)}" data-action="expense" data-key="${esc(k.ad)}">${esc(t(k.ad))} ↗</button>`,money(total),pct(Core.ratio(total,r.total))]}),[t('Toplam'),money(r.total),r.total>0?'100%':'—'])}`}
function workCard(k){const value=Core.ratio(k.gerc,k.proje);return `<article class="work-card" id="${Core.id('site',k.name)}"><header><h3>${esc(t(k.name))}</h3>${icon('site',16)}</header><div class="percent num">${pct(value)}</div>${progress(value,'blue')}<p class="meta">${fmt(k.gerc)} / ${fmt(k.proje)} ${esc(t(k.unit))}</p><button class="btn ghost" data-action="site" data-key="${esc(k.name)}">${t('Detayı aç')}${icon('arrow',16)}</button></article>`}
function site(){const p=DATA.personel;return `<div class="section-row" style="margin-top:0"><h2>${t('İş grupları')}</h2><button class="link-btn" data-action="reorder" data-key="saha">${icon('sort')}${t('Sıralama')}</button></div><div class="card-grid">${ordered(DATA.sahaItems,'saha',x=>x.name).map(workCard).join('')||empty()}</div><div class="section-row"><h2>${t('Personel Durumu')}</h2><span class="badge">${t('Rapor tarihi')}: ${esc(DATA.meta.date)}</span></div><div class="panel" id="personnel"><div class="panel-head"><h2>${t('Toplam Personel')}</h2><div class="contract-total" style="margin:0">${fmt(p.toplam)}</div></div><div class="personnel-grid">${[['ESTA Direkt',p.estaDirekt],['ESTA Endirekt',p.estaEndirekt],['Taşeron Direkt',p.taseronDirekt],['Taşeron Endirekt',p.taseronEndirekt],['Make',p.make],['Endirekt Oranı',pct(p.oran)]].map(([l,v])=>`<div><small>${t(l)}</small><strong class="num">${typeof v==='number'?fmt(v):v}</strong></div>`).join('')}</div><p class="meta" style="margin-top:18px">${t('Endirekt Oranı')}: ${t('ESTA Endirekt')} / (${t('ESTA Direkt')} + ${t('ESTA Endirekt')})</p></div>`}
function graphs(){const cats=DATA.harcamalar?.kategoriler||[];return `<div class="filters">${periodButtons()}</div><div class="panel"><div class="panel-head"><h2>${t('Genel Karşılaştırma')}</h2></div><div class="chips" style="margin-bottom:20px">${[['harcama','Toplam Harcama'],['tahsilat','Tahsilat'],['hakedis','Brüt Hakediş']].map(([key,label],i)=>`<button class="chip ${state.general.includes(key)?'active':''}" data-action="general" data-key="${key}" aria-pressed="${state.general.includes(key)}"><i style="--series:${COLORS[i]}"></i>${t(label)}</button>`).join('')}</div>${generalChart('general')}<p class="meta">${t('Eksik aylar sıfır kabul edilmez.')}</p></div><div class="section-row"><h2>${t('Harcama Kalemleri Karşılaştırma')}</h2></div><div class="panel"><div class="chips" style="margin-bottom:24px">${cats.map((k,i)=>`<button class="chip ${state.categories.includes(k.ad)?'active':''}" data-action="category" data-key="${esc(k.ad)}" aria-pressed="${state.categories.includes(k.ad)}"><i style="--series:${COLORS[i%COLORS.length]}"></i>${esc(t(k.ad))}</button>`).join('')}</div>${chart('categories',...trimSeries(DATA.harcamalar?.aylar||[],cats.map((k,i)=>({label:k.ad,values:k.aylik,color:COLORS[i%COLORS.length]})).filter(k=>state.categories.includes(k.label))))}</div>`}
function openDialog(title,body,focusSelector){dialogOpener=document.activeElement;const d=$('#dialog');d.innerHTML=`<div class="dialog-head"><h2 id="dialogTitle">${esc(t(title))}</h2><button class="icon-btn" data-action="close" aria-label="${t('Kapat')}">${icon('close')}</button></div><div class="dialog-body">${body}</div>`;if(!d.open)d.showModal();(focusSelector?d.querySelector(focusSelector):d.querySelector('button'))?.focus()}
function closeDialog(){const d=$('#dialog');d.close()}
$('#dialog').addEventListener('close',()=>{if(dialogOpener?.isConnected)dialogOpener.focus();else $('#main').focus({preventScroll:true})});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
function notify(message){$('#notice').textContent=t(message);$('#notice').classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('visible'),5000)}
function formula(name){const g=DATA.gauges.find(x=>x.label===name);if(!g)return;const s=Core.gaugeStats(g,DATA);openDialog('Hesaplama',`<h3>${esc(t(g.label))}</h3>${kv('Tutar',money(s.value))}${kv(s.base,money(s.target))}${kv('Oran',pct(s.pct))}<div class="info-line">${icon('info')}<span>${money(s.value)} / ${money(s.target)} × 100 = ${pct(s.pct)}${s.pct===null?'<br>'+t('Hedef tanımlı değil'):''}</span></div>${['Toplam Tahsilat','Saha Tahakkuk','Brüt Hakediş'].includes(name)?kv('Sözleşme oranı',pct(s.contractPct)):''}${name==='Toplam Harcama'?kv('Proje Transfer',String(g.sub||'').replace('Proje Transfer','').trim()):''}<p class="meta">${t('Rapor tarihi')}: ${esc(DATA.meta.date)}</p>`)}
function siteDetail(name){const k=DATA.sahaItems.find(x=>x.name===name);if(!k)return;const u=t(k.unit);openDialog(t(k.name),`${kv('Proje Metraj',fmt(k.proje)+' '+u)}${kv('Gerçekleşen',fmt(k.gerc)+' '+u)}${kv('Kalan (Toplam)',fmt(k.kalan)+' '+u)}${kv('Bu Ay Planlanan',fmt(k.ay.plan)+' '+u)}${kv('Bu Ay Gerçekleşen',fmt(k.ay.gerc)+' '+u)}${kv('Bu Ay Kalan',fmt(k.ay.kalan)+' '+u)}${kv('Haftalık Ortalama',fmt(k.haftalik)+' '+u)}${kv('Oran',pct(Core.ratio(k.gerc,k.proje)))}`)}
function paymentDetail(name){const k=Core.monthlyCategories(DATA).find(x=>x.name===name);if(!k)return;openDialog(t(name),`<div class="contract-total">${money(k.total)}</div>${table(['Ay','Brüt Hakediş'],k.months.map(m=>[esc(month(m.month)),money(m.value)]),'',false)}`)}
function expenseDetail(name){const k=DATA.harcamalar?.kategoriler.find(x=>x.ad===name);if(!k)return;const r=range();openDialog(t(name),`<p class="meta">${esc(month(r.months[r.start]))} — ${esc(month(r.months[r.end]))}</p><div class="contract-total">${money(Core.sum(k.aylik.slice(r.start,r.end+1)))}</div>${table(['Ay','Tutar'],r.months.slice(r.start,r.end+1).map((m,i)=>[esc(month(m)),money(k.aylik[r.start+i])]),'',false)}${k.altKalemler?.length?`<div class="section-row"><h2>${t('Alt kalemler (seçili dönem toplamı)')}</h2></div>${table(['Kalem','Tutar'],k.altKalemler.map(a=>[esc(t(a.ad)),money(Core.sum(a.aylik.slice(r.start,r.end+1)))]),'',false)}`:''}`)}
function chartData(key,index){const c=chartRegistry[key];if(!c)return;if(index!=null){openDialog(month(c.months[index]),c.series.map(s=>kv(s.label,money(s.values[index]))).join(''));return}openDialog('Grafik verileri',`<p class="meta" style="margin-bottom:16px">${t('Tutarlar milyon RUB (₽)')}</p>${table(['Ay',...c.series.map(s=>s.label)],c.months.map((m,i)=>[esc(month(m)),...c.series.map(s=>fmt(s.values[i]))]),'',false)}`)}
function buildSearch(){const list=NAV.map(([key,label])=>({label,route:key,tag:'Sekme'}));list.push({label:'Personel',route:'saha',target:'personnel',tag:'Personel'});DATA.gauges.forEach(g=>list.push({label:g.label,route:'ozet',target:Core.id('gauge',g.label),action:'formula',key:g.label,tag:'Gösterge'}));DATA.sahaItems.forEach(k=>list.push({label:k.name,route:'saha',target:Core.id('site',k.name),action:'site',key:k.name,tag:'Saha'}));DATA.hakedisTipleri.forEach(([name])=>list.push({label:name,route:'acikisler',target:Core.id('open',name),tag:'Açık İşler'}));(DATA.harcamalar?.kategoriler||[]).forEach(k=>list.push({label:k.ad,route:'harcamalar',target:Core.id('expense',k.ad),action:'expense',key:k.ad,tag:'Harcama'}));Core.monthlyCategories(DATA).forEach(k=>list.push({label:k.name,route:'hakedis',action:'payment',key:k.name,tag:'Hakediş'}));DATA.aylikDagilim.forEach(m=>list.push({label:m.ay,route:'hakedis',action:'month',key:m.ay,tag:'Ay'}));DATA.kesintiler.forEach(([label])=>list.push({label,route:'hakedis',tag:'Kesinti'}));DATA.avansSummary.concat(DATA.bankaGarantili,DATA.bankaGarantisiz).forEach(([label])=>list.push({label,route:'avans',tag:'Avans'}));searchIndex=list}
function search(){openDialog('Ara',`<label class="field"><span class="meta">${t('Rapor içinde ara…')}</span><input type="search" id="searchInput" class="search-field" autocomplete="off" placeholder="${t('Rapor içinde ara…')}"></label><div class="search-results" id="searchResults" aria-live="polite"><p class="meta">${t('Aramak için bir kelime yaz.')}</p></div>`,'#searchInput')}
function searchResults(q){const normalize=s=>String(s).toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');const query=normalize(q.trim());const results=query?searchIndex.map((x,i)=>({...x,i})).filter(x=>normalize(x.label+' '+t(x.label)+' '+month(x.label)).includes(query)).slice(0,30):[];$('#searchResults').innerHTML=!query?`<p class="meta">${t('Aramak için bir kelime yaz.')}</p>`:results.length?results.map(x=>`<button class="search-result" data-action="search-result" data-index="${x.i}"><span>${esc(x.tag==='Ay'?month(x.label):t(x.label))}</span><small>${t(x.tag)}</small></button>`).join(''):`<p class="meta">${t('Sonuç bulunamadı')}</p>`}
function goSearch(index){const item=searchIndex[index];if(!item)return;closeDialog();const show=()=>{if(item.action==='month'){const m=DATA.aylikDagilim.find(x=>x.ay===item.key);openDialog(month(item.key),table(['Kalem','Tutar'],m.kalemler.map(([k,v])=>[esc(t(k)),money(v)]),'',false));}else if(item.action)action(item.action,item.key);else if(item.target){const el=document.getElementById(item.target);el?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});el?.classList.add('highlight');el?.setAttribute('tabindex','-1');el?.focus({preventScroll:true});setTimeout(()=>el?.classList.remove('highlight'),2200)}};if(state.route!==item.route){window.addEventListener('hashchange',show,{once:true});location.hash=item.route}else show()}
let reorderKind='gauge';
function reorderData(kind){return kind==='nav'?NAV.map(x=>({id:x[0],label:x[1]})):kind==='gauge'?DATA.gauges.map(x=>({id:x.label,label:x.label})):kind==='saha'?DATA.sahaItems.map(x=>({id:x.name,label:x.name})):kind==='acik'?DATA.hakedisTipleri.map(x=>({id:x[0],label:x[0]})):(DATA.harcamalar?.kategoriler||[]).map(x=>({id:x.ad,label:x.ad}))}
function reorder(kind='gauge',retain=false){reorderKind=kind;const entries=ordered(reorderData(kind),kind,x=>x.id);const body=`<p class="meta" style="margin-bottom:16px">${t('Sıralamayı bu cihaz için düzenle.')}</p><label class="field">${t('Bölümler')}<select id="reorderKind">${[['gauge','Göstergeler'],['nav','Menü'],['saha','Saha'],['acik','Açık İşler'],['harcama','Harcamalar']].map(([k,l])=>`<option value="${k}" ${kind===k?'selected':''}>${t(l)}</option>`).join('')}</select></label><div id="reorderList">${entries.map((x,i)=>`<div class="reorder-row" draggable="true" data-id="${esc(x.id)}"><span>${esc(t(x.label))}</span><button class="icon-btn" data-action="move-up" data-key="${esc(x.id)}" aria-label="${esc(t(x.label)+' · '+t('Yukarı taşı'))}" ${i===0?'disabled':''}>${icon('up')}</button><button class="icon-btn" data-action="move-down" data-key="${esc(x.id)}" aria-label="${esc(t(x.label)+' · '+t('Aşağı taşı'))}" ${i===entries.length-1?'disabled':''}>${icon('down')}</button></div>`).join('')}</div><div class="dialog-actions"><button class="btn" data-action="reset-order">${t('Varsayılana dön')}</button><button class="btn primary" data-action="close">${t('Tamam')}</button></div>`;if(retain)$('#dialog .dialog-body').innerHTML=body;else openDialog('Düzeni düzenle',body)}
function moveOrder(key,delta){const arr=ordered(reorderData(reorderKind),reorderKind,x=>x.id).map(x=>x.id);const index=arr.indexOf(key),to=index+delta;if(index<0||to<0||to>=arr.length)return;[arr[index],arr[to]]=[arr[to],arr[index]];save(ORDER_KEYS[reorderKind],arr);render();reorder(reorderKind,true);const buttons=Array.from($('#reorderList').querySelectorAll('button'));buttons.find(b=>b.dataset.key===key&&b.dataset.action===(delta<0?'move-up':'move-down')&&!b.disabled)?.focus()}
function more(){openDialog('Menü',`<nav class="nav-list">${ordered(NAV,'nav',x=>x[0]).map(([key,label,img])=>`<button class="nav-link ${state.route===key?'active':''}" data-action="goto" data-key="${key}">${icon(img)}${t(label)}</button>`).join('')}</nav><div class="dialog-actions"><button class="btn" data-action="reorder">${icon('sort')}${t('Düzeni düzenle')}</button><button class="btn" data-action="logout">${icon('logout')}${t('Çıkış Yap')}</button></div>`)}
function reportOptions(){openDialog('Rapor seçenekleri',`<label class="field">${t('Dil')}<select id="reportLang"><option value="tr" ${state.lang==='tr'?'selected':''}>Türkçe</option><option value="ru" ${state.lang==='ru'?'selected':''}>Русский</option></select></label><label class="field">KDV<select id="reportVat"><option value="kdvsiz" ${state.vat==='kdvsiz'?'selected':''}>${t("KDV'siz")}</option><option value="kdvli" ${state.vat==='kdvli'?'selected':''}>${t("KDV'li")}</option></select></label><h3>${t('Bölümler')}</h3>${NAV.map(([key,label])=>`<label class="check-row"><input type="checkbox" name="reportSection" value="${key}" checked>${t(label)}</label>`).join('')}<p class="meta" style="margin-top:20px">${t('PDF olarak kaydetmek için yazdırma penceresinde PDF hedefini seç.')}</p><div class="dialog-actions"><button class="btn" data-action="print">${t('PDF / Yazdır')}</button><button class="btn primary" id="downloadPdf" data-action="download-pdf">${icon('download')}${t('PDF indir')}</button></div>`)}
function buildPrint(sections,lang,vat){const previous=state.lang;state.lang=lang;try{const d=DATA,r=range();const tab=(headers,rows)=>`<table><thead><tr>${headers.map(h=>`<th>${esc(t(h))}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;let body='';for(const section of sections){let content='';if(section==='ozet'){content=`<h2>${t('Sözleşmeler')}</h2>${tab(['Kalem','Tutar'],[[t('Güncel Sözleşme Bedeli'),money(d.contractCurrent.total)],...d.contractCurrent.items.map(([l,v])=>[t(l),money(v)]),[t('Toplam Potansiyel Sözleşme Bedeli'),money(d.contractPotential.total)],...d.contractPotential.items.map(([l,v])=>[t(l),money(v)])])}<h2>${t('Finansal Göstergeler')}</h2>${tab(['Kalem','Tutar','Oran','Hesaplama tabanı'],d.gauges.map(g=>{const s=Core.gaugeStats(g,d);return [t(g.label),money(g.big),pct(s.pct),t(s.base)]}))}<h2>${t('Süreç Takvimi')}</h2>${tab(['Kalem','Rapor tarihi','Kalan'],[['CMP',d.kalanGun.cmpTarih,fmt(d.kalanGun.cmpGun)],['PNR',d.kalanGun.pnrTarih,fmt(d.kalanGun.pnrGun)]])}<p>${t('Geçen gün oranı')} (PNR): ${pct(d.kalanGun.gecenPnr)}</p>`}
if(section==='avans'){content=`<p>${t(vat==='kdvli'?"KDV'li":"KDV'siz")}</p>`;for(const [label,rows,pi] of [['Severstal Avans Tablosu',d.avansSummary,2],['Banka Garantili',d.bankaGarantili,1],['Banka Garantisiz',d.bankaGarantisiz,1]])content+=`<h2>${t(label)}</h2>${tab(['Kalem','Tutar','Oran'],rows.map((row,i)=>[t(row[0]),money(row[vat==='kdvli'?2:1]),i===pi?pct(Core.ratio(Core.parseM(row[1]),Core.parseM(rows[0][1]))):row[3]==null?'—':pct(row[3])]))}`;content+=tab(['Kalem','Tutar'],[[t('Potansiyel Düşülecek Banka Mektubu'),money(d.potansiyelDusulecek[vat])]])}
if(section==='hakedis')content=tab(['Kalem','Tutar'],[[t('Brüt Hakediş'),money(d.brutHakedisToplam)],...d.brutHakedisDetay.map(([l,v])=>[t(l),money(v)]),...d.kesintiler.map(([l,v])=>[t(l),money(v)])])+`<h2>${t('Brüt Hakediş Aylık Dağılım')}</h2>`+tab(['Ay','Brüt Hakediş'],d.monthlyBrut.map(m=>[month(m.m),money(m.v)]))+`<h2>${t('Tahsilat ve Net Hakediş')}</h2>`+tab(['Ay','Tahsilat','Net Hakediş'],d.monthlyNet.map(m=>[month(m.m),money(m.tahsilat),money(m.net)]))+Core.monthlyCategories(d).map(k=>`<h2>${esc(t(k.name))} · ${money(k.total)}</h2>${tab(['Ay','Tutar'],k.months.map(m=>[month(m.month),money(m.value)]))}`).join('');
if(section==='acikisler')content=tab(['Kalem','Finansal İlerleme','Brüt Hakediş','Fark','Oran'],[...d.hakedisTipleri.map(([l,a,b])=>[t(l),money(a),money(b),money(Core.parseM(a)-Core.parseM(b)),pct(Core.ratio(Core.parseM(b),Core.parseM(a)))]),...Object.entries(d.hakedisTotals).map(([k,v])=>[t(k==='kdvli'?"Toplam (KDV'li)":'Toplam (KDV hariç)'),money(v.finansal),money(v.brut),money(Core.parseM(v.finansal)-Core.parseM(v.brut)),pct(Core.ratio(Core.parseM(v.brut),Core.parseM(v.finansal)))])]);
if(section==='saha')content=`<h2>${t('Personel Durumu')}</h2>${tab(['Kalem','Toplam'],[['Toplam Personel',d.personel.toplam],['ESTA Direkt',d.personel.estaDirekt],['ESTA Endirekt',d.personel.estaEndirekt],['Taşeron Direkt',d.personel.taseronDirekt],['Taşeron Endirekt',d.personel.taseronEndirekt],['Make',d.personel.make],['Endirekt Oranı',pct(d.personel.oran)]].map(([l,v])=>[t(l),typeof v==='number'?fmt(v):v]))}${d.sahaItems.map(k=>`<h2>${esc(t(k.name))} (${esc(t(k.unit))})</h2>${tab(['Kalem','Tutar'],[['Proje Metraj',k.proje],['Gerçekleşen',k.gerc],['Kalan (Toplam)',k.kalan],['Bu Ay Planlanan',k.ay.plan],['Bu Ay Gerçekleşen',k.ay.gerc],['Bu Ay Kalan',k.ay.kalan],['Haftalık Ortalama',k.haftalik]].map(([l,v])=>[t(l),fmt(v)]))}`).join('')}`;
if(section==='harcamalar')content=!d.harcamalar?`<p>${t('Veri yok')}</p>`:`<p>${t('Seçili harcama dönemi')}: ${month(r.months[r.start]||'')} — ${month(r.months[r.end]||'')}</p><p>${t('Toplam')}: ${money(r.total)}</p>${d.harcamalar.kategoriler.map(k=>`<h2>${esc(t(k.ad))} · ${money(Core.sum(k.aylik.slice(r.start,r.end+1)))}</h2>${tab(['Ay','Tutar'],r.months.slice(r.start,r.end+1).map((m,i)=>[month(m),money(k.aylik[r.start+i])]))}${k.altKalemler?.length?tab(['Kalem','Dönem toplamı'],k.altKalemler.map(a=>[t(a.ad),money(Core.sum(a.aylik.slice(r.start,r.end+1)))])):''}`).join('')}`;
if(section==='grafikler'){const g=Core.generalSeries(d);const [months,series]=trimSeries(g.months,g.series.filter(s=>state.general.includes(s.key)));content=`<p>${t('Grafik verileri')} · ${t(state.period==='all'?'Tüm dönem':`Son ${state.period} Ay`)}</p>`+tab(['Ay',...series.map(s=>s.label)],months.map((m,i)=>[month(m),...series.map(s=>money(s.values[i]))]));const cats=(d.harcamalar?.kategoriler||[]).filter(k=>state.categories.includes(k.ad));content+=cats.map(k=>{const [ms,ss]=trimSeries(d.harcamalar.aylar,[{values:k.aylik}]);return `<h2>${esc(t(k.ad))}</h2>${tab(['Ay','Tutar'],ms.map((m,i)=>[month(m),money(ss[0].values[i])]))}`}).join('')}
body+=`<section class="print-section"><h2>${t(titles[section])}</h2>${content}</section>`}return `<header><img src="icon-shield.png" alt="ESTA"><div><h1>ESTA · ${esc(d.meta.project)}</h1><p>${t('Finans ve saha raporu')} · ${t('Rapor tarihi')}: ${esc(d.meta.date)}</p><p>${t('Tutarlar milyon RUB (₽)')}</p></div></header><p class="print-note">${t('Finansal tutarlar rapor tarihine aittir. Grafikler kendi kayıt dönemini gösterir.')}</p>${body}`;}finally{state.lang=previous}}
function printReport(){const sections=Array.from(document.querySelectorAll('[name=reportSection]:checked')).map(x=>x.value);if(!sections.length){notify('En az bir bölüm seç.');return}$('#printReport').innerHTML=buildPrint(sections,$('#reportLang').value,$('#reportVat').value);closeDialog();document.title=`ESTA-${DATA.meta.project}-${DATA.meta.date}`;requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()))}
async function logout(){notify('Çıkış yapılıyor');try{if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('esta-110sppc-')).map(k=>caches.delete(k)))}if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>r.scope===new URL('./',location.href).href).map(r=>r.unregister()))}}finally{location.replace('/cdn-cgi/access/logout')}}
function action(name,key,index){if(!DATA&&!['lang','theme','refresh','close','logout','reload'].includes(name))return;switch(name){case'close':closeDialog();break;case'theme':state.theme=state.theme==='dark'?'light':'dark';save('esta_theme_pref',state.theme);shell();break;case'lang':state.lang=state.lang==='tr'?'ru':'tr';save('esta_lang_pref',state.lang);if($('#dialog').open)closeDialog();DATA?render():shell();break;case'refresh':loadData(true);break;case'reload':location.reload();break;case'goto':if($('#dialog').open)closeDialog();if(state.route===key){window.scrollTo({top:0,behavior:'instant'})}else location.hash=key;break;case'more':more();break;case'search':search();break;case'search-result':goSearch(Number(index));break;case'formula':formula(key);break;case'contracts':openDialog('Sözleşme detayları',contract(DATA.contractCurrent)+'<hr style="border:0;border-top:1px solid var(--border);margin:20px 0">'+contract(DATA.contractPotential)+kv('Bütçe',money(DATA.butce)));break;case'period':state.period=key;render();break;case'vat':state.vat=key;render();break;case'site':siteDetail(key);break;case'payment':paymentDetail(key);break;case'expense':expenseDetail(key);break;case'chart-data':chartData(key);break;case'chart-point':chartData(key,Number(index));break;case'general':state.general=state.general.includes(key)?state.general.filter(k=>k!==key):[...state.general,key];render();break;case'category':state.categories=state.categories.includes(key)?state.categories.filter(k=>k!==key):[...state.categories,key];render();break;case'expense-period':{const months=DATA.harcamalar.aylar;state.start=months[key==='all'?0:Math.max(0,months.length-Number(key))];state.end=months.at(-1);render();break}case'sort-open':state.sort.open=state.sort.open==='value'?'custom':'value';render();break;case'sort-expense':state.sort.expense=state.sort.expense==='value'?'custom':'value';render();break;case'reorder':reorder(key||'gauge');break;case'move-up':moveOrder(key,-1);break;case'move-down':moveOrder(key,1);break;case'reset-order':save(ORDER_KEYS[reorderKind],[]);render();reorder(reorderKind,true);break;case'report':reportOptions();break;case'print':printReport();break;case'download-pdf':downloadPDF();break;case'logout':logout();break}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const focused=el===document.activeElement,act=el.dataset.action,key=el.dataset.key;action(act,key,el.dataset.index);if(focused&&!el.isConnected&&!$('#dialog').open){const replacement=Array.from(document.querySelectorAll('[data-action]')).find(x=>x.dataset.action===act&&x.dataset.key===key);replacement?.focus({preventScroll:true})}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput')searchResults(e.target.value)});
document.addEventListener('change',e=>{if(e.target.id==='rangeStart'||e.target.id==='rangeEnd'){const r=range();if(e.target.id==='rangeStart'){state.start=e.target.value;if(r.months.indexOf(state.start)>r.end)state.end=state.start}else{state.end=e.target.value;if(r.months.indexOf(state.end)<r.start)state.start=state.end}const id=e.target.id;render();document.getElementById(id)?.focus()}if(e.target.id==='reorderKind')reorder(e.target.value,true)});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(DATA)search()}if(e.target.matches('.chart-dot')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();action(e.target.dataset.action,e.target.dataset.key,e.target.dataset.index)}if($('#dialog').open&&$('#searchInput')&&(e.key==='ArrowDown'||e.key==='ArrowUp')){const nodes=[$('#searchInput'),...document.querySelectorAll('.search-result')],i=nodes.indexOf(document.activeElement);e.preventDefault();nodes[(i+(e.key==='ArrowDown'?1:-1)+nodes.length)%nodes.length]?.focus()}});
let dragId=null;
document.addEventListener('dragstart',e=>{const row=e.target.closest('.reorder-row');if(!row)return;dragId=row.dataset.id;e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';row.classList.add('dragging')});
document.addEventListener('dragover',e=>{if(dragId&&e.target.closest('.reorder-row'))e.preventDefault()});
document.addEventListener('drop',e=>{const target=e.target.closest('.reorder-row');if(!target||!dragId)return;e.preventDefault();const arr=ordered(reorderData(reorderKind),reorderKind,x=>x.id).map(x=>x.id),from=arr.indexOf(dragId),to=arr.indexOf(target.dataset.id);if(from>=0&&to>=0){arr.splice(from,1);arr.splice(to,0,dragId);save(ORDER_KEYS[reorderKind],arr);render();reorder(reorderKind,true)}dragId=null});
document.addEventListener('dragend',()=>{dragId=null;document.querySelectorAll('.dragging').forEach(x=>x.classList.remove('dragging'))});
async function loadData(manual=false){if(state.busy)return;state.busy=true;shell();if(DATA){render();$('#main').setAttribute('aria-busy','true')}const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const res=await fetch('data.json',{cache:'no-store',signal:controller.signal,credentials:'same-origin'});if(res.status===401||res.status===403)throw Error('auth');if(!res.ok)throw Error('http');const type=res.headers.get('Content-Type')||'';if(type.includes('text/html'))throw Error('auth');const candidate=Core.validate(await res.json());DATA=candidate;state.source=res.headers.get('X-ESTA-Source')==='cache'?'cache':'network';state.received=new Date().toISOString();if(state.categories===null)state.categories=[...(DATA.harcamalar?.kategoriler||[])].sort((a,b)=>b.odenen-a.odenen).slice(0,4).map(k=>k.ad);else state.categories=state.categories.filter(name=>(DATA.harcamalar?.kategoriler||[]).some(k=>k.ad===name));state.busy=false;render();if(manual)notify(state.source==='cache'?'Son kayıtlı rapor':'Rapor yenilendi')}catch(error){state.busy=false;if(DATA){render();notify('Yenileme başarısız; mevcut rapor gösteriliyor.')}else{shell();const message=String(error.message).startsWith('schema')?'Rapor verisinin yapısı beklenen biçimde değil.':error.message==='auth'?'Oturum sona ermiş olabilir. Yeniden giriş için sayfayı aç.':'Rapor şu anda yüklenemiyor. Bağlantını kontrol edip tekrar dene.';$('#main').innerHTML=`<div class="panel">${empty('Veri alınamadı',message)}<div style="text-align:center;margin-bottom:24px"><button class="btn primary" data-action="${error.message==='auth'?'reload':'refresh'}">${icon('refresh')}${t(error.message==='auth'?'Raporu yeniden aç':'Tekrar dene')}</button></div></div>`;$('#main').setAttribute('aria-busy','false')}}finally{clearTimeout(timeout)}}
window.addEventListener('hashchange',route);
window.addEventListener('online',()=>{shell();loadData()});window.addEventListener('offline',()=>{if(DATA)render();else shell()});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&DATA&&navigator.onLine&&Date.now()-Date.parse(state.received)>300000)loadData()});
window.addEventListener('afterprint',()=>{$('#printReport').innerHTML='';document.title='ESTA · '+(DATA?.meta.project||'110 SPPC')});
route();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
loadData();
